Import unit administrative
zinza-d2-training/thanhpc-nestjs pull request #4
Opened 2022-03-14 11:41 UTC by cthanh2310

closes #3

2022-03-18 14:33 UTC, hungnp194 requested changes

2022-03-18 14:33 UTC, hungnp194 commented on .env.example
> +MYSQL_LOGGING=true
```suggestion
PORT=3000

MYSQL_HOST=localhost
MYSQL_PORT=3306
MYSQL_USERNAME=root
MYSQL_PASSWORD=
MYSQL_DATABASE=covid_tracker
MYSQL_LOGGING=true
```

2022-03-18 14:33 UTC, hungnp194 commented on .gitignore
> +.env
```suggestion
.env

```

2022-03-18 14:33 UTC, hungnp194 commented on src/app.module.ts
> +import { TypeormModule } from './typeorm/typeorm.module';
```suggestion
import { TypeormModule } from './typeorm/typeorm.module';

```

2022-03-18 14:33 UTC, hungnp194 commented on src/entities/Province.ts
> +    type: 'bigint',
```suggestion
    type: 'int',
```

2022-03-18 14:33 UTC, hungnp194 commented on src/entities/Province.ts
> +    nullable: false,
```suggestion
```

2022-03-18 14:33 UTC, hungnp194 commented on src/entities/District.ts
> +  province_id: number;
```suggestion
  provinceId: number;
```

2022-03-18 14:33 UTC, hungnp194 commented on src/entities/Ward.ts
> +  district_id: number;
```suggestion
  districtId: number;
```

2022-03-18 14:33 UTC, hungnp194 commented on src/export-unit-administrative/services/export-unit-administrative/export-unit-administrative.service.ts
> +    desc: 'Test Command',
Viết đúng desc

2022-03-18 14:33 UTC, hungnp194 commented on src/export-unit-administrative/types/District.ts
> +  updatedAt?: Date;
Viết cùng 1 convention camelCase

2022-03-18 14:33 UTC, hungnp194 commented on src/export-unit-administrative/types/Province.ts
> +}
Viết cùng 1 convention camelCase

2022-03-18 14:33 UTC, hungnp194 commented on src/export-unit-administrative/types/Ward.ts
> +}
Viết cùng 1 convention camelCase

2022-03-18 14:33 UTC, hungnp194 commented on src/main.ts
> +  await app.listen(process.env.PORT);
```suggestion
  await app.listen(process.env.PORT || 3000);
```

2022-03-18 14:33 UTC, hungnp194 commented on src/typeorm/ormconfig.ts
> +console.log('__dirname', __dirname);
```suggestion

```

2022-03-18 14:33 UTC, hungnp194 commented on src/typeorm/typeorm.module.ts
> +    }),
```suggestion
```

2022-03-18 14:33 UTC, hungnp194 commented on src/utils/.~lock.unitAdministrative.xls#
> +,thanhpham,thanhpham-Latitude-E7440,15.03.2022 09:28,file:///home/thanhpham/.config/libreoffice/4;
?

2022-03-20 08:08 UTC, cthanh2310 commented on src/app.module.ts
> +import { TypeormModule } from './typeorm/typeorm.module';
Em không hiểu lắm ạ

2022-03-20 08:09 UTC, cthanh2310 commented on .gitignore
> +.env
Em không hiểu lắm ạ

2022-03-20 08:09 UTC, cthanh2310 commented on src/app.module.ts
> +import { TypeormModule } from './typeorm/typeorm.module';
Em không hiểu lắm ạ

2022-03-21 02:51 UTC, hungnp194 commented on src/entities/District.ts
> +  createdAt: Date;
```suggestion
  created_at: Date;
```

2022-03-21 03:27 UTC, hungnp194 requested changes

2022-03-21 03:27 UTC, hungnp194 commented on src/entities/District.ts
> +  createdAt: Date;
Viết cùng 1 convention

2022-03-21 03:27 UTC, hungnp194 commented on src/entities/Ward.ts
> +    type: 'bigint',
```suggestion
    type: 'int',
```

2022-03-21 03:27 UTC, hungnp194 commented on src/entities/District.ts
> +  createdAt: Date;
Sửa tất cả các file cần sửa

2022-03-21 03:27 UTC, hungnp194 commented on src/typeorm/migrations/1647255273188-WardsMigration.ts
> +// Site manager	Number of vaccination table ??
```suggestion
```

2022-03-21 03:27 UTC, hungnp194 commented on src/typeorm/migrations/1647500628164-CitizenImagesMigration.ts
> +          },
column này có tác dụng gì?

2022-03-21 03:27 UTC, hungnp194 commented on src/typeorm/migrations/1647500628164-CitizenImagesMigration.ts
> +          },
Thiếu citizen_id

2022-03-21 03:27 UTC, hungnp194 commented on src/typeorm/migrations/1647500919549-InjectionHistoriesMigration.ts
> +            name: 'injected_vaccine_name_id',
```suggestion
            name: 'injected_vaccine_id',
```

2022-03-21 03:27 UTC, hungnp194 commented on src/typeorm/migrations/1647500919549-InjectionHistoriesMigration.ts
> +            columnNames: ['injected_vaccine_name_id'],
```suggestion
            columnNames: ['injected_vaccine_id'],
```

2022-03-21 03:27 UTC, hungnp194 commented on src/typeorm/migrations/1647501456818-UsersMigration.ts
> +          { name: 'citizen_image_id', type: 'int', length: '11' },
```suggestion
```

2022-03-21 03:27 UTC, hungnp194 commented on src/typeorm/migrations/1647501456818-UsersMigration.ts
> +          { name: 'dob', type: 'timestamp' },
```suggestion
          { name: 'dob', type: 'date' },
```

2022-03-21 03:27 UTC, hungnp194 commented on src/typeorm/migrations/1647501456818-UsersMigration.ts
> +          { name: 'gender', type: 'varchar', length: '11' },
```suggestion
          { name: 'gender', type: 'tinyint', length: '4' },
```

2022-03-21 03:27 UTC, hungnp194 commented on src/typeorm/migrations/1647501456818-UsersMigration.ts
> +          },
```suggestion
```

2022-03-21 03:27 UTC, hungnp194 commented on src/typeorm/migrations/1647501456818-UsersMigration.ts
> +          { name: 'injection_history_id', type: 'int', length: '11' },
Quan hệ 1-n

2022-03-21 03:27 UTC, hungnp194 commented on src/typeorm/migrations/1647502202200-MedicalHistoryResponsesMigration.ts
> +            name: 'status_injection_registration',
```suggestion
            name: 'injection_registration_status',
```

2022-03-21 03:27 UTC, hungnp194 commented on src/typeorm/migrations/1647502202200-MedicalHistoryResponsesMigration.ts
> +            length: '255',
```suggestion
            type: 'tinyint',
            length: '4',
```

2022-03-21 03:27 UTC, hungnp194 commented on src/typeorm/migrations/1647502202200-MedicalHistoryResponsesMigration.ts
> +        name: 'medical_history_responses',
- Thiếu bảng câu hỏi
- n - 1 bảng questions
- n - 1 bảng phiếu tiêm

2022-03-21 03:27 UTC, hungnp194 commented on src/typeorm/migrations/1647502324071-PersonalInformationsMigration.ts
> +          { name: 'dob', type: 'timestamp' },
```suggestion
          { name: 'dob', type: 'date' },
```

2022-03-21 03:27 UTC, hungnp194 commented on src/typeorm/migrations/1647502324071-PersonalInformationsMigration.ts
> +          },
```suggestion
            name: 'expected_date',
            type: 'date',
            length: '255',
            isNullable: true,
          },
```

2022-03-21 10:07 UTC, hungnp194 approved these changes

2022-03-21 10:08 UTC, merged